### ISSUE TITLE
今天突然又报错了

### ISSUE THREAD

**Issue by kanvenzeng** [CenBoMin/JDTASK_V2P#8]
已经稳定运行好多天了，今天突然报以下错误，麻烦大佬看看。(看了jsmanage变量那里是正常的)
ReferenceError: $env is not defined
    at RunJDTaskV2P.js:2:14
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at /usr/local/app/script/runJSFile.js:214:24
    at new Promise (<anonymous>)
    at runJS (/usr/local/app/script/runJSFile.js:185:10)
    at /usr/local/app/script/runJSFile.js:322:5
    at new Promise (<anonymous>)
    at runJSFile (/usr/local/app/script/runJSFile.js:321:10)
[taskRunJS   info][2021-08-16 17:20:00.016] run RunJDTaskV2P.js result: {"error":"$env is not defined"}
[RunJD...js error][2021-08-16 17:20:00.012] RunJDTaskV2P.js:2
let jstask = $env.JDTASK

**Comment by CenBoMin** [comment]
@kanvenzeng 我是拉docker镜像就可以了，软更新错误可以看下elecv2p项目的我提问题的issue，大佬有回复

**Comment by kanvenzeng** [comment]
> @kanvenzeng 我是拉docker镜像就可以了，软更新错误可以看下elecv2p项目的我提问题的issue，大佬有回复

谢谢大佬，果然重新拉镜像就解决了。

**Comment by CenBoMin** [comment]
@kanvenzeng 呵呵 不客气
